name: Build executables

on: push

jobs:
  build-linux-x64-executable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install Nodejs dependencies
        run: npm ci --legacy-peer-deps

      - name: Transpile code to JavaScript
        run: npm run transpile

      - name: Build executable
        run: npm run build-linux-x64

      - name: Setup Git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit files
        run: |
          git checkout -b pages
          rm -rf docs
          mv dist docs
          git add -f ./docs
          git commit -m "Add build"
          git push -f origin pages
